version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_ml
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fastapi-app:
    build: .
    container_name: property-friends-container
    restart: always
    depends_on:
      - mongodb
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/logs_db

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge