name: Test and Deploy

on:
  push:
    branches:
      - master

jobs:
  train_model:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AKI }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Print all environment variables
        run: printenv

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKI }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}
        run: echo "AWS credentials configured"

      - name: Get Data from S3
        run: python property_friends_real_state/modeling/get_data.py

      - name: Train Model
        run: python property_friends_real_state/modeling/train.py

      - name: Evaluate Model
        run: python property_friends_real_state/modeling/predict.py

      - name: Save trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: property_friends_real_state/app/model.pkl  # Ensure this path is correct

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: property_friends_real_state/app/  # Ensure this path is used in Docker build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Tag Docker Compose Package
        run: |
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app-compose
            docker build --no-cache -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(date +%Y%m%d%H%M%S)
  
      - name: Push Docker Compose Package to GHCR
        run: |
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app-compose
            docker push $IMAGE_NAME --all-tags